spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare


server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://casual-kodiak-85.clerk.accounts.dev
clerk.jwks-url=https://casual-kodiak-85.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_m8wLRqv7F9RMTvliFs5GMnBtWeA94DZ/